version: "3.8"

services: 
  web:
    build: .
    ports:
      - "4401:4401"
    environment:
      - PORT=4401
      - NODE_ENV=production
      - dbPort=5432
      - dbName=postgres
      - dbPassword=postgres
      - secretKey=53sssaaa
      - dbDatabse=curs
      - IS_DOCKER=true
    restart: always
    links:
     - postgres:db
    depends_on:
     - postgres

  postgres:
    image: postgres:12
    restart: always
    volumes:
     - ./volumes/init.sql:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=curs