version: "3.8"

volumes: 
  dbdata: {}

services: 
  web:
    build: .
    ports:
      - "4401:4401"
    environment:
      - PORT=4401
      - NODE_ENV=production
      - dbPort=5432
      - dbName=postgres
      - dbPassword=postgres
      - secretKey=53sssaaa
      - dbDatabse=curs
      - IS_DOCKER=true
    restart: always
    links:
     - postgres
    depends_on:
     - postgres

  postgres:
    image: postgres:12
    restart: always
    volumes:
     - ./volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
     - dbdata:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=curs