// USER
export const USER_SET_DATA = "USER_SET_DATA";
export const USER_SET_LOADING = "USER_SET_LOADING";
export const USER_SET_ERROR = "USER_SET_ERROR";

// RECIPE
export const RECIPE_SET_CATEGOIES = "RECIPE_SET_CATEGOIES";
export const RECIPE_SET_LOADING = "RECIPE_SET_LOADING";
export const RECIPE_SET_FILTER = "RECIPE_SET_FILTER";
export const RECIPE_SET_RECIPES = "RECIPE_SET_RECIPES";
export const RECIPE_ADD_RECIPES = "RECIPE_ADD_RECIPES";
export const RECIPE_STEP_BACK = "RECIPE_STEP_BACK";
export const RECIPE_STEP_NEXT = "RECIPE_STEP_NEXT";
export const RECIPE_CLEAR_FOR_FETCH = "RECIPE_CLEAR_FOR_FETCH";
export const RECIPE_SET_ONE_RECIPE = "RECIPE_SET_ONE_RECIPE";
export const RECIPE_ADD_COMMENT_TO_RECEPT = "RECIPE_ADD_COMMENT_TO_RECEPT";
export const RECIPE_DELETE_COMMENT = "RECIPE_DELETE_COMMENT";
export const RECIPE_DELETE_RECIPE = "RECIPE_DELETE_RECIPE";